name: Issue Management Automation

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Process Bug Report
        if: |
          contains(github.event.issue.labels.*.name, 'bug') && 
          github.event.action == 'opened'
        run: |
          echo "Processing bug report #${{ github.event.issue.number }}"
          # 添加评论
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d '{"body":"### Bug Report Guidelines\n\nPlease ensure you include:\n1. Steps to reproduce\n2. Expected behavior\n3. Actual behavior\n4. Screenshots if applicable\n5. Environment details"}'

      - name: Process Feature Request
        if: |
          contains(github.event.issue.labels.*.name, 'epic') && 
          github.event.action == 'opened'
        run: |
          echo "Processing feature request #${{ github.event.issue.number }}"
          # 添加评论
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d '{"body":"### Feature Request Process\n\nThis epic will be broken down into subtasks. Please ensure each subtask references this parent issue."}'

      - name: Process Maintenance Request
        if: |
          contains(github.event.issue.labels.*.name, 'maintenance') && 
          github.event.action == 'opened'
        run: |
          echo "Processing maintenance request #${{ github.event.issue.number }}"
          # 添加评论
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d '{"body":"### Maintenance Guidelines\n\nPlease provide:\n1. Documentation sections to update\n2. Proposed structure changes\n3. Content recommendations"}'
